name-template: 'Release v$NEXT_PATCH_VERSION ğŸ‰'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ New Features'
    labels:
      - feature
  - title: 'ğŸ› Bug Fixes'
    labels:
      - bug
  - title: 'ğŸ“ Documentation Updates'
    labels:
      - documentation
  - title: 'ğŸ§ª Tests'
    labels:
      - tests
change-template: '- $TITLE (#$NUMBER) @${{ USER }}'
no-changes-template: 'No changes in this release.'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPO/compare/$PREVIOUS_TAG...$NEW_TAG
